-- migrate:up
CREATE TABLE IF NOT EXISTS "roles" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "uq_roles_name" ON "roles" ("name");

-- migrate:down
DROP TABLE IF EXISTS "roles";
