-- migrate:up
CREATE TABLE IF NOT EXISTS "users" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY,
    "email" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "display_name" VARCHAR(255) NULL DEFAULT NULL,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "uq_users_email" ON "users" ("email");
CREATE INDEX IF NOT EXISTS "idx_users_is_active" ON "users" ("is_active");

CREATE OR REPLACE TRIGGER "users_updated_at"
    BEFORE UPDATE
    ON "users"
    FOR EACH ROW
EXECUTE PROCEDURE moddatetime("updated_at");

-- migrate:down
DROP TABLE IF EXISTS "users";
