INSERT INTO "villas" ("name", "details", "rate", "square_feet", "occupancy", "image_url")
VALUES ('Royal Villa',
        'Luxurious villa with stunning ocean views and private beach access.',
        500.0,
        2500,
        6,
        'https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa1.jpg'),
       ('Diamond Villa',
        'Elegant villa with marble interiors and panoramic mountain views.',
        750.0,
        3200,
        8,
        'https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa2.jpg'),
       ('Pool Villa',
        'Modern villa featuring an infinity pool and outdoor entertainment area.',
        350.0,
        1800,
        4,
        'https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa3.jpg'),
       ('Luxury Villa',
        'Premium villa with spa facilities and concierge services.',
        900.0,
        4000,
        10,
        'https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa4.jpg'),
       ('Garden Villa',
        'Charming villa surrounded by tropical gardens and nature trails.',
        275.0,
        1500,
        3,
        'https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa5.jpg')
;